classDiagram

namespace PkgQcm {
  class Apprenant 
  class Qcm
  class Question
  class OptionQuestion
  class ReponseQcm
  class ReponseQuestion
  class BrancheQuestion
}

%% type : Choix unique , choix multiple
class Question{
  type : string 


}

class ReponseQuestion {
  duree : int
}


OptionQuestion --> Question
ReponseQuestion --> Question
BrancheQuestion --> "*" Question
ReponseQuestion <-- Apprenant
ReponseQuestion --> "*" OptionQuestion
Qcm --> BrancheQuestion
Apprenant --> ReponseQcm
ReponseQcm --> Qcm



